# Variable 'IsGenerateBased' was defined in the Variables tab
# Variable 'NugetSecurityAnalysisWarningLevel' was defined in the Variables tab
# Variable 'OCTOKITPAT' was defined in the Variables tab
# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location

jobs:
- job: Job_1
  displayName: Main
  timeoutInMinutes: 120
  pool: pool-windows-2019
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: Run CredScan
    condition: in(variables['system.pullRequest.targetBranch'], 'generation', 'main')
    inputs:
      toolMajorVersion: V2
      outputFormat: sarif
      scanFolder: SecurityTmp
      suppressionsFile: tools/SecurityTools/CredScanSuppressions.json
